# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - GraphWebApi/*
      - GraphSnippetsReflection/*

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    vsVersion: 'latest'
    solution: '**\*.sln'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'

- task: VisualStudioTestPlatformInstaller@1
  displayName: 'Install VSTest Platform'
  inputs:
    versionSelector: latestStable
    packageFeedSelector: nugetOrg
    testPlatformVersion: 16.9.4

- task: DotNetCoreCLI@2
  displayName: "Run Tests"
  continueOnError: true
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage" --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-build'

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: '**/*.trx' 
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'
    failTaskOnFailedTests: false # Optional
    publishRunAttachments: true # Optional

- task: DotNetCoreCLI@2
  displayName: 'Publish Artifacts'
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    arguments: '--configuration $(buildConfiguration) --no-build --nologo --output $(Build.ArtifactStagingDirectory) '

- task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
  displayName: 'Graph Client Tooling pipeline fail notification'
  inputs:
    addressType: serviceEndpoint
    serviceEndpointName: 'microsoftgraph pipeline status'
    title: '$(Build.DefinitionName) failure notification'
    text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
  condition: failed()
  enabled: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)//GraphExplorerApi.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

