# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline for Snippet injection into docs

trigger: none
pr: none
schedules:
  - cron: "30 12 * * 2"
    displayName: Weekly Tuesday snippets updates
    branches:
      include:
      - master
    always: true

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: main

pool:
  vmImage: 'ubuntu-latest'


parameters:
  - name: snippetLanguages
    type: object
    default: ['C#', 'CLI', 'Go', 'Java', 'JavaScript', 'PHP', 'PowerShell', 'Python'] # should be ordered alphabetically
    displayName: 'Languages to generate snippets for'

variables:
  buildConfiguration: 'Release'
  apidoctorPath: 'microsoft-graph-devx-api/apidoctor'
  apidoctorProjects: '$(apidoctorPath)/**/*.csproj'
  snippetLanguages: ${{ join(',',parameters.snippetLanguages) }}

stages:
- stage: GenerateSnippets
  displayName: Generate snippets
  jobs:
  - job: GenerateSnippets
    displayName: Generate snippets
    steps:
    - checkout: self
      displayName: checkout GE api
      fetchDepth: 1
      submodules: recursive
      persistCredentials: true

    - checkout: microsoft-graph-docs
      displayName: checkout docs
      fetchDepth: 1
      persistCredentials: true

    - pwsh: |
        # override branch prefix incase the run is manually triggered
        $branchPrefix = if ($env:BUILD_REASON -eq 'Manual') { "preview-snippet-generation" } else { "snippet-generation" }
        Write-Host "##vso[task.setvariable variable=branchPrefix]$branchPrefix"
        Write-Host "Branch prefix is $branchPrefix"
      displayName: 'Evaluate branch prefix to use'

    - template: templates/git-config.yml

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK 6'
      inputs:
        version: 6.x

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK 7'
      inputs:
        version: 7.0.x

    - task: DotNetCoreCLI@2
      displayName: 'Build snippet generator'
      inputs:
        command: 'build'
        projects: 'microsoft-graph-devx-api/CodeSnippetsReflection.App/CodeSnippetsReflection.App.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages for APIDoctor'
      inputs:
        command: 'restore'
        projects: '$(Build.SourcesDirectory)/$(apidoctorProjects)'

    - task: DotNetCoreCLI@2
      displayName: 'Build APIDoctor'
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/$(apidoctorProjects)'
        arguments: '--configuration $(buildConfiguration)'

    - pwsh: |
        # release folder can change based on .NET core version, so search recursively in bin folder
        $snippetGeneratorPath = (Get-ChildItem $env:BUILD_SOURCESDIRECTORY/microsoft-graph-devx-api/CodeSnippetsReflection.App/bin/Release *App -Recurse).FullName
        Write-Host "Path to snippet generator tool: $snippetGeneratorPath"

        $apidoctorPath = (Get-ChildItem $env:BUILD_SOURCESDIRECTORY/microsoft-graph-devx-api/apidoctor/ApiDoctor.Console/bin/Release apidoc -Recurse).FullName
        Write-Host "Path to apidoctor tool: $apidoctorPath"

        . $apidoctorPath generate-snippets --ignore-warnings --path . --snippet-generator-path $snippetGeneratorPath --temp-output-path $env:BUILD_ARTIFACTSTAGINGDIRECTORY/Snippets --lang $(snippetLanguages) --git-path "/bin/git"
      displayName: 'Generate snippets'
      workingDirectory: microsoft-graph-docs

    - task: PublishBuildArtifacts@1
      displayName: 'Publish snippets as artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Snippets'
        ArtifactName: 'Snippets'
        publishLocation: 'Container'
        StoreAsTar: true

    - template: templates/commit-changes.yml
- stage: RunTests
  dependsOn: GenerateSnippets
  displayName: Run tests
  jobs:
  - job: RunTests
    strategy:
      matrix:
        'HTTP v1':
          SNIPPET_LANGUAGE: 'http'
          GRAPH_VERSION: 'v1'
        'HTTP beta':
          SNIPPET_LANGUAGE: 'http'
          GRAPH_VERSION: 'beta'
        ${{ each language in parameters.snippetLanguages }}:
          '${{ language }} v1':
            SNIPPET_LANGUAGE: ${{ lower(language) }}
            GRAPH_VERSION: 'v1'
          '${{ language }} beta':
            SNIPPET_LANGUAGE: ${{ lower(language) }}
            GRAPH_VERSION: 'beta'

    steps:
    - template: templates/run-tests.yml
    
    
    
