# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline for Snippet injection into docs

trigger: none
pr: none
schedules:
  - cron: "30 12 * * 2"
    displayName: Weekly Tuesday snippets updates
    branches:
      include:
      - master
    always: true

pool:
  name: 1es-ubuntu-latest


parameters:
  - name: extractBuildId
    type: string
    default: "155605"
    displayName: 'BuildId for run with artifacts'
  - name: 'version'
    type: string
    default: "8.x"

variables:
  extractBuildId: ${{parameters.extractBuildId}}

stages:
- stage: GenerateRunTestReports
  displayName: GenerateRunTestReports
  jobs:
  - job: GenerateCategorizationReport
    steps:
      - checkout: self
        displayName: checkout GE api
        fetchDepth: 1
        submodules: recursive
        persistCredentials: true

      - pwsh: |
          Write-Host "##vso[task.setvariable variable=pwshver;]$($PSVersionTable.PSVersion)"
          Write-Host "Running PowerShell Version: $($PSVersionTable.PSVersion)"
        displayName: 'Check PS Version'

      - task: UseDotNet@2
        displayName: 'Use .NET SDK'
        inputs:
          packageType: sdk
          version: ${{ parameters.version }}
          performMultiLevelLookup: true
          includePreviewVersions: true
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - pwsh: |
          Write-Host "Initial Version: $(pwshver)"
          dotnet tool install --global PowerShell --version 7.3.3
          Write-Host "Updated to Version: 7.3.3"
          exit
        condition: 'lt(variables.pwshver, 7.3)'
        displayName: 'Upgrade PS Version if less than 7.3'

      - pwsh: |
          $(Build.SourcesDirectory)/scripts/downloadArtifacts.ps1 -buildId $(extractBuildId)
        env:
          AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
          WORKING_DIRECTORY: $(Build.SourcesDirectory)
          ARTIFACTS_DIRECTORY: $(Build.ArtifactStagingDirectory)
        displayName: 'Download and extract artifact'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download RunTests artifact'
        inputs:
          artifact: 'Generation Test Results'
          path: '$(Build.ArtifactStagingDirectory)/TestResults'

      - pwsh: |
          Write-Host "Installing module ImportExcel"
          Install-Module -Name ImportExcel -Scope CurrentUser -Force -AllowClobber
          Write-Host "Installing module Microsoft.Graph"
          Install-Module Microsoft.Graph -Repository PSGallery -Scope CurrentUser -AcceptLicense -Force -AllowClobber
          Write-Host "Finished installing dependencies"
        displayName: Install script dependencies
        workingDirectory: '$(Build.SourcesDirectory)'

      - pwsh: |
          Write-Host "create file appSettings.json in the workingDirectory"
          New-Item -Path $(Build.SourcesDirectory) -Name "appSettings.json" -ItemType "file" -Force
          Write-Host "Creating folder Reports"
          New-Item -Path $(Build.SourcesDirectory) -Name "Reports" -ItemType "Directory" -Force
        displayName: Create requisite directory items

      - task: AzurePowerShell@5
        inputs:
          azureSubscription: "RaptorServiceFederationConnection"
          ScriptType: "FilePath"
          ScriptPath: "$(Build.SourcesDirectory)/scripts/categorizeErrors.ps1"
          ScriptArguments: "
            -trxFolderPath '$(Build.ArtifactStagingDirectory)/TestResults/' 
            -txtOutputFolderPath '$(Build.ArtifactStagingDirectory)/Reports/'
            "
          workingDirectory: '$(Build.SourcesDirectory)'
          pwsh: true
          azurePowerShellVersion: latestVersion
        displayName: Generate error category report
        env:
          RAPTOR_CONFIGENDPOINT: $(RAPTOR_CONFIGENDPOINT)
          RAPTOR_CONFIGMANAGEDIDENTITY_ID: $(RAPTOR_CONFIGMANAGEDIDENTITY_ID)
        continueOnError: true

      # - pwsh: |
      #     $ErrorActionPreference="Continue"
      #      -trxFolderPath '$(Build.ArtifactStagingDirectory)/TestResults/' -txtOutputFolderPath '$(Build.ArtifactStagingDirectory)/Reports/'
      #   displayName: Generate error category report
      #   workingDirectory: '$(Build.SourcesDirectory)'
      #   env:
      #     RAPTOR_CONFIGENDPOINT: $(RAPTOR_CONFIGENDPOINT)
      #     RAPTOR_CONFIGMANAGEDIDENTITY_ID: $(RAPTOR_CONFIGMANAGEDIDENTITY_ID)
      #   continueOnError: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish categorization report as artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Reports/'
          ArtifactName: 'ErrorCategorizationReport'
          publishLocation: 'Container'
