# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline for removing unused snippets from the docs repo

trigger: none
pr: none
schedules:
  - cron: "30 12 * * 3"
    displayName: Weekly Wednesday unused snippets removal
    branches:
      include:
      - master
    always: true

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: checkout GE api
  fetchDepth: 1
  persistCredentials: true

- checkout: microsoft-graph-docs
  displayName: checkout docs
  fetchDepth: 1
  persistCredentials: true

- pwsh: |
    # override branch prefix incase the run is manually triggered
    $branchPrefix = if ($env:BUILD_REASON -eq 'Manual') { "preview-remove-unused-snippets" } else { "remove-unused-snippets" }
    Write-Host "##vso[task.setvariable variable=branchPrefix]$branchPrefix"
    Write-Host "Branch prefix is $branchPrefix"
  displayName: 'Evaluate branch prefix to use'
  
- template: templates/git-config.yml

- pwsh: $(Build.SourcesDirectory)/microsoft-graph-devx-api/scripts/cleanupUnusedSnippets.ps1
  displayName: 'Cleanup unused snippets'
  workingDirectory: microsoft-graph-docs

- template: templates/commit-changes.yml
